"""baseline schema (wraps 001_init_schema.sql)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-18

This revision is a one-time baseline. It applies the hand-written SQL file
`migrations/001_init_schema.sql` verbatim and provides a fully reversible
`downgrade()` that drops every table in the correct foreign-key order.

All subsequent migrations MUST be proper Alembic operations generated by
`make migrate-new MSG="..."` — never another raw SQL file.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables listed in reverse FK-dependency order so DROP succeeds.
_TABLES_IN_DROP_ORDER: tuple[str, ...] = (
    "audit_logs",
    "notification_batches",
    "notifications",
    "fcm_tokens",
    "media_files",
    "conversation_members",
    "message_reads",
    "messages",
    "conversations",
    "group_members",
    "topics",
    "groups",
    "user_roles",
    "role_permissions",
    "permissions",
    "roles",
    "refresh_tokens",
    "user_invitations",
    "users",
    "institutions",
)


def _baseline_sql() -> str:
    """Read the baseline SQL file. Kept as a function for testability."""
    path = Path(__file__).resolve().parents[1] / "001_init_schema.sql"
    return path.read_text(encoding="utf-8")


def upgrade() -> None:
    """Create all baseline tables by executing the canonical SQL file."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    op.execute(_baseline_sql())


def downgrade() -> None:
    """Drop every baseline table in reverse FK order.

    Explicitly tested: calling `alembic downgrade base` must leave a clean
    database with no tables from this schema.
    """
    for table in _TABLES_IN_DROP_ORDER:
        op.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE;')
