"""baseline schema (wraps 001_init_schema.sql)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-18

This revision is a one-time baseline. It applies the hand-written SQL file
`migrations/001_init_schema.sql` verbatim and provides a fully reversible
`downgrade()` that drops every table in the correct foreign-key order.

All subsequent migrations MUST be proper Alembic operations generated by
`make migrate-new MSG="..."` — never another raw SQL file.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables listed in reverse FK-dependency order so DROP succeeds.
_TABLES_IN_DROP_ORDER: tuple[str, ...] = (
    "audit_logs",
    "notification_batches",
    "notifications",
    "fcm_tokens",
    "media_files",
    "conversation_members",
    "message_reads",
    "messages",
    "conversations",
    "group_members",
    "topics",
    "groups",
    "user_roles",
    "role_permissions",
    "permissions",
    "roles",
    "refresh_tokens",
    "user_invitations",
    "users",
    "institutions",
)


def _baseline_sql() -> str:
    """Read the baseline SQL file. Kept as a function for testability."""
    path = Path(__file__).resolve().parents[1] / "001_init_schema.sql"
    return path.read_text(encoding="utf-8")


def _split_statements(sql: str) -> list[str]:
    """Split a SQL script into individual statements.

    Needed because asyncpg's prepared-statement API cannot execute multiple
    statements in one call. We respect:
      - line comments (``--``)
      - dollar-quoted bodies (``$$ ... $$`` used in trigger functions)
      - simple string literals
    """
    statements: list[str] = []
    buf: list[str] = []
    in_dollar = False
    in_line_comment = False
    in_string = False

    i = 0
    while i < len(sql):
        ch = sql[i]
        nxt = sql[i + 1] if i + 1 < len(sql) else ""

        if in_line_comment:
            buf.append(ch)
            if ch == "\n":
                in_line_comment = False
            i += 1
            continue

        if not in_dollar and not in_string and ch == "-" and nxt == "-":
            in_line_comment = True
            buf.append(ch)
            i += 1
            continue

        if not in_string and ch == "$" and nxt == "$":
            in_dollar = not in_dollar
            buf.append("$$")
            i += 2
            continue

        if not in_dollar and ch == "'":
            in_string = not in_string
            buf.append(ch)
            i += 1
            continue

        if ch == ";" and not in_dollar and not in_string:
            stmt = "".join(buf).strip()
            if stmt:
                statements.append(stmt)
            buf = []
            i += 1
            continue

        buf.append(ch)
        i += 1

    tail = "".join(buf).strip()
    if tail:
        statements.append(tail)
    return statements


def upgrade() -> None:
    """Create all baseline tables by executing the canonical SQL file."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    for stmt in _split_statements(_baseline_sql()):
        op.execute(stmt)


def downgrade() -> None:
    """Drop every baseline table in reverse FK order.

    Explicitly tested: calling `alembic downgrade base` must leave a clean
    database with no tables from this schema.
    """
    for table in _TABLES_IN_DROP_ORDER:
        op.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE;')
